name: comment trigger
on:
  issue_comment:
    types: [created, deleted, edited]
jobs:
  check-pr:
    if: github.event.issue.pull_request && github.event.comment.user.login == 'hdr-balance-backroom'
    name: Trigger recheck of backroom approval
    runs-on: ubuntu-latest
    steps:
      - name: reopen PR to trigger recheck
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'character change'
            }).then(() => {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['character change']
              })
            }).catch(e => console.error(e))